application: wclstats
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:  
- url: /stylesheets
  static_dir: stylesheets
  
- url: /resources
  static_dir: resources

- url: /.*
  script: wclstats.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
